console.log("Hallo");
console.log("Tolle Sache");
let a = 7;
let b = 8;
let c = 10;
console.log(a + b + c);
console.log((a + b) / c);
console.log(c - a + b);
console.log(a + b + c * 3);
console.log((a + b + c) / 4);
console.log(a = 3);
console.log(b = a + 3);
console.log(c = c - 3);
